# tox configuration - if you change anything here, run this to verify: tox --recreate

[tox]
envlist = py{310,311,312,313,314},flake8,mypy

[testenv]
deps =
    pytest
    requests
    boto3
    paramiko
commands = pytest -v -rs tests
pass_env =
    BORGSTORE_TEST_*_URL

[testenv:flake8]
skip_sdist=true
skip_install=true
changedir =
deps = flake8-pyproject
commands = flake8 src

[testenv:mypy]
changedir =
deps =
    mypy
    requests
    boto3
    paramiko
    types-requests
    types-boto3
    types-paramiko
commands = mypy
